stages:
  - test

test:
  stage: test
  image: elixir:1.9.4
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - _build/
  before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  script:
  - mix test --trace
  variables:
    MIX_ENV: test

dialyzer:
  stage: test
  image: elixir:1.9.4
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - _build/
  before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  script:
  - mix dialyzer
  variables:
    MIX_ENV: dev
