stages:
  - test
  - deploy

test:
  stage: test
  image: elixir:1.9.4
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - _build/
  before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  script:
  - mix test --trace --cover
  variables:
    MIX_ENV: test
  artifacts:
    paths:
      - cover/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv cover/ public/
  artifacts:
    expire_in: 30 days
    paths:
      - public
  only:
    - master

dialyzer:
  stage: test
  image: elixir:1.9.4
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - _build/
  before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  script:
  - mix dialyzer
  variables:
    MIX_ENV: dev
